#!/usr/bin/env bash
# =========================================================================
# matugen-apply (mac) — 現在のデスクトップ壁紙から matugen でパレットを抽出し、
# 各アプリへ展開する。WSL版 (modules/theming/matugen/wsl/matugen-apply.sh) の
# Mac向け簡略版 (YASB/komorebi/ロック画面等 Windows専用部分を除いたもの)。
# =========================================================================
# 呼び出し:
#   matugen-apply             現在の壁紙 (System Events経由) を自動検出して適用
#   matugen-apply <画像パス>   指定した画像で適用
#   matugen-apply --reapply   前回の壁紙で再生成 (テンプレート更新の反映用)
set -euo pipefail

export PATH="$HOME/.nix-profile/bin:/opt/homebrew/bin:$PATH"

# 多重起動ガード (壁紙切り替え時の二重実行対策)。macOSに`flock`が無いため
# `mkdir`のアトミック性を使った簡易ロックにする (WSL/Linuxの`flock`と役割は同じ)。
mkdir -p "$HOME/.cache/matugen"
LOCK_DIR="$HOME/.cache/matugen/.apply.lock.d"
for _ in $(seq 1 50); do
    mkdir "$LOCK_DIR" 2>/dev/null && break
    sleep 0.1
done
trap 'rmdir "$LOCK_DIR" 2>/dev/null || true' EXIT

CACHE="$HOME/.cache/matugen/mac-palette.css"

# -------------------------------------------------------------------------
# 1. 壁紙の決定と matugen 実行
# -------------------------------------------------------------------------
if [[ "${1:-}" == "--reapply" ]]; then
    img=""
    [[ -f "$HOME/.cache/matugen/last-wallpaper" ]] && img="$(cat "$HOME/.cache/matugen/last-wallpaper")"
    [[ -f "$img" ]] || img=""
elif [[ -n "${1:-}" ]]; then
    img="$1"
else
    # 現在のデスクトップ壁紙のパスを取得する (初回はSystem Eventsのオートメーション許可が必要)
    img="$(osascript -e 'tell application "System Events" to tell first desktop to get picture' 2>/dev/null || true)"
fi

if [[ -z "${img:-}" || ! -f "$img" ]]; then
    echo "matugen-apply: 壁紙画像が見つからないため中断しました (img=${img:-<empty>})" >&2
    exit 1
fi

matugen image "$img" -m dark --source-color-index 0 \
    -c "$HOME/.config/matugen-mac/config.toml"
printf '%s\n' "$img" > "$HOME/.cache/matugen/last-wallpaper"

# -------------------------------------------------------------------------
# 2. パレット抽出 (WSL版と同じCSS変数名 → Material role の対応)
# -------------------------------------------------------------------------
pal() { grep -m1 -- "--$1:" "$CACHE" 2>/dev/null | grep -oE '#[0-9a-fA-F]{6}' || true; }

LIB="$HOME/.config/matugen-common/lib"
TPL="$HOME/.config/matugen-common/templates"

[[ -f "$CACHE" ]] || { echo "matugen-apply: $CACHE が生成されなかった" >&2; exit 1; }

accent="$(pal highlight)"
tertiary="$(pal accent-sub)"
secondary="$(pal secondary)"
text="$(pal text)"
muted="$(pal subtext1)"
surface="$(pal surface2)"
on_accent="$(pal base)"
error="$(pal red)"
outline="$(pal subtext0)"

if [[ -z "$accent" || -z "$tertiary" || -z "$secondary" || -z "$text" \
      || -z "$muted" || -z "$surface" || -z "$on_accent" ]]; then
    echo "matugen-apply: パレット抽出に失敗した (必須キー欠落)" >&2
    exit 1
fi

base_lua="$(mktemp)"
cat > "$base_lua" <<EOF
return {
  accent = "${accent}",
  tertiary = "${tertiary}",
  secondary = "${secondary}",
  text = "${text}",
  muted = "${muted}",
  surface = "${surface}",
  on_accent = "${on_accent}",
  error = "${error}",
}
EOF
python3 "$LIB/derive-colors.py" "$base_lua"
pal_lua() { grep -m1 "^\s*$1\s*=" "$base_lua" | grep -oE '#[0-9a-fA-F]{6}'; }
complement="$(pal_lua complement)"
triad="$(pal_lua triad)"
accent_pale="$(pal_lua accent_pale)"
[[ -n "$accent_pale" ]] || accent_pale="#c7dffe"
[[ -n "$complement" ]] || complement="#f2d4ad"
[[ -n "$triad" ]] || triad="#f2adcb"
[[ -n "$error" ]] || error="#ffb4ab"
[[ -n "$outline" ]] || outline="#c3c6cf"
selection_bg="$surface"

lua_tmp="$(mktemp)"
cat > "$lua_tmp" <<LUA
-- Generated by matugen-apply (mac) — do not edit
return {
  accent = "${accent}",
  tertiary = "${tertiary}",
  secondary = "${secondary}",
  complement = "${complement}",
  triad = "${triad}",
  text = "${text}",
  muted = "${muted}",
  surface = "${surface}",
  on_accent = "${on_accent}",
  accent_pale = "${accent_pale}",
  error = "${error}",
  selection_bg = "${selection_bg}",
}
LUA
rm -f "$base_lua"

# -------------------------------------------------------------------------
# 3. 各アプリへの展開 (WSL版 セクション5〜9と同じ内容、Windows固有部分を除く)
# -------------------------------------------------------------------------
command mkdir -p "$HOME/.config/wezterm"
command cp -f "$lua_tmp" "$HOME/.config/wezterm/matugen-colors.lua"
command cp -f "$lua_tmp" "$HOME/.cache/matugen/colors.lua"

STARSHIP_OUT="$HOME/.cache/matugen/starship.toml"
"$LIB/render-template.sh" "$TPL/starship.toml" "$STARSHIP_OUT" "$lua_tmp"
"$LIB/render-template.sh" "$TPL/lazygit-theme.yml" \
    "$HOME/.cache/matugen/lazygit-theme.yml" "$lua_tmp"
"$LIB/render-template.sh" "$TPL/cz.toml" \
    "$HOME/.cache/matugen/cz.toml" "$lua_tmp"
if [[ -f "$HOME/.config/yazi/theme-template.toml" ]]; then
    "$LIB/render-template.sh" "$HOME/.config/yazi/theme-template.toml" \
        "$HOME/.config/yazi/theme.toml" "$lua_tmp"
fi

mkdir -p "$HOME/.cache/matugen/eza"
"$LIB/render-template.sh" "$TPL/eza-theme.yml" \
    "$HOME/.cache/matugen/eza/theme.yml" "$lua_tmp"

mkdir -p "$HOME/.cache/matugen/tealdeer"
python3 "$LIB/tealdeer-config.py" "$lua_tmp" "$HOME/.cache/matugen/tealdeer/config.toml"

mkdir -p "$HOME/.config/atuin/themes" "$HOME/.config/btop/themes"
"$LIB/render-template.sh" "$TPL/atuin-theme.toml" \
    "$HOME/.config/atuin/themes/matugen.toml" "$lua_tmp"
"$LIB/render-template.sh" "$TPL/btop.theme" \
    "$HOME/.config/btop/themes/matugen.theme" "$lua_tmp"

cat > "$HOME/.cache/matugen/fzf-colors.sh.tmp" <<SH
# Generated by matugen-apply (mac) — do not edit
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --highlight-line --color=pointer:${accent},marker:${accent},prompt:${accent},info:${tertiary},hl:${tertiary},hl+:${tertiary},bg+:${selection_bg},spinner:${tertiary}'
SH
mv "$HOME/.cache/matugen/fzf-colors.sh.tmp" "$HOME/.cache/matugen/fzf-colors.sh"

rm -f "$lua_tmp"

# -------------------------------------------------------------------------
# 4. AeroSpace (JankyBorders) の枠色を追従させる
# -------------------------------------------------------------------------
[[ -x "$HOME/.local/bin/aerospace-launch-borders" ]] && \
    "$HOME/.local/bin/aerospace-launch-borders" || true

echo "matugen-apply (mac): 適用完了 (accent=${accent})"
